import Navbar from "@/components/ui/Dashboard/Navbar/Navbar";
import Sidebar from "@/components/ui/Dashboard/SideBar/Sidebar";


export const metadata = {
    title: "Vlearn",
    description: "Generated by Vlearn",
};
export default function DashboardLayout({ children }) {
    return (
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
            <Sidebar />
            <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                <Navbar />
                {children}
            </div>
        </div>

    );
}
