import Navbar from "@/components/ui/Dashboard/Navbar/Navbar";
import Sidebar from "@/components/ui/Dashboard/SideBar/Sidebar";


export const metadata = {
    title: "Vlearn",
    description: "Generated by Vlearn",
};
export default function ProjectDetailsLayout({ children }) {
    return (
        <>
            {children}
        </>


    );
}
